// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file apiary/v1/models.proto (package apiary.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apiary/v1/models.proto.
 */
export const file_apiary_v1_models: GenFile = /*@__PURE__*/
  fileDesc("ChZhcGlhcnkvdjEvbW9kZWxzLnByb3RvEglhcGlhcnkudjEiIwoFRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgMQmEKDWNvbS5hcGlhcnkudjFCC01vZGVsc1Byb3RvUAGiAgNBWFiqAglBcGlhcnkuVjHKAglBcGlhcnlcVjHiAhVBcGlhcnlcVjFcR1BCTWV0YWRhdGHqAgpBcGlhcnk6OlYxYgZwcm90bzM");

/**
 * @generated from message apiary.v1.Entry
 */
export type Entry = Message<"apiary.v1.Entry"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: bytes value = 2;
   */
  value: Uint8Array;
};

/**
 * Describes the message apiary.v1.Entry.
 * Use `create(EntrySchema)` to create a new message.
 */
export const EntrySchema: GenMessage<Entry> = /*@__PURE__*/
  messageDesc(file_apiary_v1_models, 0);

