// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file apiary/v1/requests.proto (package apiary.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Entry } from "./models_pb";
import { file_apiary_v1_models } from "./models_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apiary/v1/requests.proto.
 */
export const file_apiary_v1_requests: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGlhcnkvdjEvcmVxdWVzdHMucHJvdG8SCWFwaWFyeS52MSIzChFHZXRFbnRyaWVzUmVxdWVzdBIQCghrZXlzcGFjZRgBIAEoCRIMCgRrZXlzGAIgAygJIkgKEVNldEVudHJpZXNSZXF1ZXN0EhAKCGtleXNwYWNlGAEgASgJEiEKB2VudHJpZXMYAiADKAsyEC5hcGlhcnkudjEuRW50cnkiNgoURGVsZXRlRW50cmllc1JlcXVlc3QSEAoIa2V5c3BhY2UYASABKAkSDAoEa2V5cxgCIAMoCSInChNDbGVhckVudHJpZXNSZXF1ZXN0EhAKCGtleXNwYWNlGAEgASgJQmMKDWNvbS5hcGlhcnkudjFCDVJlcXVlc3RzUHJvdG9QAaICA0FYWKoCCUFwaWFyeS5WMcoCCUFwaWFyeVxWMeICFUFwaWFyeVxWMVxHUEJNZXRhZGF0YeoCCkFwaWFyeTo6VjFiBnByb3RvMw", [file_apiary_v1_models]);

/**
 * @generated from message apiary.v1.GetEntriesRequest
 */
export type GetEntriesRequest = Message<"apiary.v1.GetEntriesRequest"> & {
  /**
   * @generated from field: string keyspace = 1;
   */
  keyspace: string;

  /**
   * @generated from field: repeated string keys = 2;
   */
  keys: string[];
};

/**
 * Describes the message apiary.v1.GetEntriesRequest.
 * Use `create(GetEntriesRequestSchema)` to create a new message.
 */
export const GetEntriesRequestSchema: GenMessage<GetEntriesRequest> = /*@__PURE__*/
  messageDesc(file_apiary_v1_requests, 0);

/**
 * @generated from message apiary.v1.SetEntriesRequest
 */
export type SetEntriesRequest = Message<"apiary.v1.SetEntriesRequest"> & {
  /**
   * @generated from field: string keyspace = 1;
   */
  keyspace: string;

  /**
   * @generated from field: repeated apiary.v1.Entry entries = 2;
   */
  entries: Entry[];
};

/**
 * Describes the message apiary.v1.SetEntriesRequest.
 * Use `create(SetEntriesRequestSchema)` to create a new message.
 */
export const SetEntriesRequestSchema: GenMessage<SetEntriesRequest> = /*@__PURE__*/
  messageDesc(file_apiary_v1_requests, 1);

/**
 * @generated from message apiary.v1.DeleteEntriesRequest
 */
export type DeleteEntriesRequest = Message<"apiary.v1.DeleteEntriesRequest"> & {
  /**
   * @generated from field: string keyspace = 1;
   */
  keyspace: string;

  /**
   * @generated from field: repeated string keys = 2;
   */
  keys: string[];
};

/**
 * Describes the message apiary.v1.DeleteEntriesRequest.
 * Use `create(DeleteEntriesRequestSchema)` to create a new message.
 */
export const DeleteEntriesRequestSchema: GenMessage<DeleteEntriesRequest> = /*@__PURE__*/
  messageDesc(file_apiary_v1_requests, 2);

/**
 * @generated from message apiary.v1.ClearEntriesRequest
 */
export type ClearEntriesRequest = Message<"apiary.v1.ClearEntriesRequest"> & {
  /**
   * @generated from field: string keyspace = 1;
   */
  keyspace: string;
};

/**
 * Describes the message apiary.v1.ClearEntriesRequest.
 * Use `create(ClearEntriesRequestSchema)` to create a new message.
 */
export const ClearEntriesRequestSchema: GenMessage<ClearEntriesRequest> = /*@__PURE__*/
  messageDesc(file_apiary_v1_requests, 3);

