// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file apiary/v1/responses.proto (package apiary.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Entry } from "./models_pb";
import { file_apiary_v1_models } from "./models_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apiary/v1/responses.proto.
 */
export const file_apiary_v1_responses: GenFile = /*@__PURE__*/
  fileDesc("ChlhcGlhcnkvdjEvcmVzcG9uc2VzLnByb3RvEglhcGlhcnkudjEiSgoSR2V0RW50cmllc1Jlc3BvbnNlEiEKB2VudHJpZXMYASADKAsyEC5hcGlhcnkudjEuRW50cnkSEQoJbm90X2ZvdW5kGAIgAygJIjgKElNldEVudHJpZXNSZXNwb25zZRISCgpzdWNjZXNzZnVsGAEgAygJEg4KBmZhaWxlZBgCIAMoCSJOChVEZWxldGVFbnRyaWVzUmVzcG9uc2USEgoKc3VjY2Vzc2Z1bBgBIAMoCRIRCglub3RfZm91bmQYAiADKAkSDgoGZmFpbGVkGAMgAygJIioKFENsZWFyRW50cmllc1Jlc3BvbnNlEhIKCnN1Y2Nlc3NmdWwYASABKAhCZAoNY29tLmFwaWFyeS52MUIOUmVzcG9uc2VzUHJvdG9QAaICA0FYWKoCCUFwaWFyeS5WMcoCCUFwaWFyeVxWMeICFUFwaWFyeVxWMVxHUEJNZXRhZGF0YeoCCkFwaWFyeTo6VjFiBnByb3RvMw", [file_apiary_v1_models]);

/**
 * @generated from message apiary.v1.GetEntriesResponse
 */
export type GetEntriesResponse = Message<"apiary.v1.GetEntriesResponse"> & {
  /**
   * @generated from field: repeated apiary.v1.Entry entries = 1;
   */
  entries: Entry[];

  /**
   * @generated from field: repeated string not_found = 2;
   */
  notFound: string[];
};

/**
 * Describes the message apiary.v1.GetEntriesResponse.
 * Use `create(GetEntriesResponseSchema)` to create a new message.
 */
export const GetEntriesResponseSchema: GenMessage<GetEntriesResponse> = /*@__PURE__*/
  messageDesc(file_apiary_v1_responses, 0);

/**
 * @generated from message apiary.v1.SetEntriesResponse
 */
export type SetEntriesResponse = Message<"apiary.v1.SetEntriesResponse"> & {
  /**
   * @generated from field: repeated string successful = 1;
   */
  successful: string[];

  /**
   * @generated from field: repeated string failed = 2;
   */
  failed: string[];
};

/**
 * Describes the message apiary.v1.SetEntriesResponse.
 * Use `create(SetEntriesResponseSchema)` to create a new message.
 */
export const SetEntriesResponseSchema: GenMessage<SetEntriesResponse> = /*@__PURE__*/
  messageDesc(file_apiary_v1_responses, 1);

/**
 * @generated from message apiary.v1.DeleteEntriesResponse
 */
export type DeleteEntriesResponse = Message<"apiary.v1.DeleteEntriesResponse"> & {
  /**
   * @generated from field: repeated string successful = 1;
   */
  successful: string[];

  /**
   * @generated from field: repeated string not_found = 2;
   */
  notFound: string[];

  /**
   * @generated from field: repeated string failed = 3;
   */
  failed: string[];
};

/**
 * Describes the message apiary.v1.DeleteEntriesResponse.
 * Use `create(DeleteEntriesResponseSchema)` to create a new message.
 */
export const DeleteEntriesResponseSchema: GenMessage<DeleteEntriesResponse> = /*@__PURE__*/
  messageDesc(file_apiary_v1_responses, 2);

/**
 * @generated from message apiary.v1.ClearEntriesResponse
 */
export type ClearEntriesResponse = Message<"apiary.v1.ClearEntriesResponse"> & {
  /**
   * @generated from field: bool successful = 1;
   */
  successful: boolean;
};

/**
 * Describes the message apiary.v1.ClearEntriesResponse.
 * Use `create(ClearEntriesResponseSchema)` to create a new message.
 */
export const ClearEntriesResponseSchema: GenMessage<ClearEntriesResponse> = /*@__PURE__*/
  messageDesc(file_apiary_v1_responses, 3);

